# Generated by Django 5.2.12 on 2026-05-06 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("properties", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rental_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property View",
                "verbose_name_plural": "Property Views",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rental_property", "created_at"],
                        name="analytics_p_rental__182eb9_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="analytics_p_user_id_616b37_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="analytics_p_ip_addr_d98333_idx",
                    ),
                ],
            },
        ),
    ]
